spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa2k3lyjrweapc7e4x7
            client-secret: w9dy84N39F6vX1y5JptBwRyxw8Jye5en5wWs1udj
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-988006.okta.com/oauth2/default