spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: react-spring-boot-app
            client-secret: e4127337-68bb-46c0-ba03-a79e5ed79c28
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: http://localhost:9080/auth/realms/tutorealm